{ config, lib, pkgs, ... }: {
  # imports = [ ./nix ./nix/home-manager.nix ];
  systemd.network = {
    enable = true;
    networks = {
      "eth0" = {
        networkConfig = {
          DHCPServer = true;
          IPv6SendRA = true;
          LLMNR = true;
        };
        dhcpServerConfig = {
          EmitDNS = true;
          EmitNTP = true;
        };
      };
    };
  };

  boot.loader.grub.enable = false;
  boot.loader.generic-extlinux-compatible.enable = true;
  boot.consoleLogLevel = lib.mkDefault 7;
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/NIXOS_SD";
      fsType = "ext4";
    };
  };

  networking = {
    hostName = "backup-rpi4";
    defaultGateway = "192.168.1.1";
    wireless = {
      enable = true;
      interfaces = [ "wlan0" ];
      networks = {
        # generated by wpa_passphrase Amber password
        Amber = {
          pskRaw =
            "099163c36ec27c3d4b5e9d8b7083ee06a415089f78bdd879bcd8c6b4b157e2a9";
        };
      };
    };
  };
  environment.systemPackages = with pkgs; [ tcpdump git vim htop ];
  users.extraUsers = { dev = { isNormalUser = true; }; };

  services = {
    openssh = {
      enable = true;
      permitRootLogin = "yes";
    };
  };

  users = {
    users = {
      root.openssh.authorizedKeys.keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKyoMfgUym3E2wsHyWEIJVPDXvGB6U6t/ciSkFtnfSeB dev@devmachine"
      ];
      "dev" = {
        isNormalUser = true;
        password = "password";
        extraGroups = [ "wheel" ];
        openssh.authorizedKeys.keys = [
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKyoMfgUym3E2wsHyWEIJVPDXvGB6U6t/ciSkFtnfSeB dev@devmachine"
        ];
      };
    };
  };

  time.timeZone = "UTC";

}
